application: mijneerstewebsite-140511
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /(.+\.(html|css|gif|png|jpg))$
  static_files: \1
  upload: .+\.(html|css|gif|png|jpg)$
  application_readable: true

- url: /.*
  static_files: opdr1.html
  upload: opdr1.html
  application_readable: true